server:
    port: 8080
    context-path: /war
spring:
  profiles: development
  data:
    mongodb:
      host: localhost
      uri: mongodb://localhost/war-deb
      database: war-deb
---
spring:
    profiles: alpha
    data:
      mongodb:
        host: localhost
        uri: mongodb://localhost/war-alpha
        database: war-alpha